### ISSUE TITLE
Script crashes on non-gpx workouts when not using -f argument

### ISSUE THREAD

**Issue by Marcski** [kjkjava/garmin-connect-export#36]
Garmin Connect activity: [1892029351] Other
        Wed, 2 Aug 2017 18:12, 00:33:18, 0.00 Miles
https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/1892029351?full=true
        Downloading file...
Traceback (most recent call last):
  File "gcexport.py", line 357, in <module>
    data = http_req(download_url)
  File "gcexport.py", line 86, in http_req
    raise Exception('Bad return code (' + str(response.getcode()) + ') for: ' + url)
Exception: Bad return code (204) for: https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/1892029351?full=true

**Comment by joetimmerman** [comment]
HI @Marcski , 

This repository is no longer being maintained. I ran into a similar issue, and have a [fork](https://github.com/joetimmerman/garmin-connect-export) that includes a "-n" option which avoids this problem by skipping validation. 

There's some discussion in [this](https://github.com/kjkjava/garmin-connect-export/issues/29) thread, and @moderation has another updated fork that should be working if mine isn't.
