### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by MrDam** [kjkjava/garmin-connect-export#41]
https://connect.garmin.com/gauth/hostname

**Comment by frechina** [comment]
definitely this is not working

**Comment by MrDam** [comment]
Traceback (most recent call last):
  File "C:\ENYDOG\GCTools\GCtoED.py", line 102, in <module>
    hostname_url = http_req('http://connect.garmin.com/gauth/hostname')
  File "C:\ENYDOG\GCTools\GCtoED.py", line 81, in http_req
    response = opener.open(request, data=post)  # This line may throw a urllib2.HTTPError.
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable

**Comment by frechina** [comment]
try https://connect.garmin.com/modern/auth/hostname

**Comment by MrDam** [comment]
Traceback (most recent call last):
  File "C:\GCtoED.py", line 179, in <module>
    http_req(url_gc_post_auth + 'ticket=' + login_ticket)
  File "C:\GCtoED.py", line 81, in http_req
    response = opener.open(request, data=post)  # This line may throw a urllib2.HTTPError.
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable

**Comment by lefty01** [comment]
fixed here:
https://github.com/pe-st/garmin-connect-export/tree/develop

**Comment by pdxvr** [comment]
FYI, I couldn't get the Python 3 version to work and the limit of 1000 activities isn't enforced, I got about 1600 in one shot.
