### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by eweiss99** [kjkjava/garmin-connect-export#44]
I've used this occasionally, but it seems to be broken now. Here's the traceback:

Traceback (most recent call last):
  File "./gcexport1.py", line 120, in <module>
    http_req(url_gc_post_auth + 'ticket=' + login_ticket)
  File "./gcexport1.py", line 71, in http_req
    response = opener.open(request, data=post)  # This line may throw a urllib2.HTTPError.
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by moderation** [comment]
@eweiss99 This repo is not maintained and wont work at all against the new API endpoints. I suggest you look at the working forks at https://github.com/moderation/garmin-connect-export/ and / or https://github.com/pe-st/garmin-connect-export

**Comment by eweiss99** [comment]
Thanks. I'll check it out.
