### ISSUE TITLE
Errors starting the py-script

### ISSUE THREAD

**Issue by beta-L-user** [kjkjava/garmin-connect-export#47]
New to Python I installed python 3.7.0,  thought it should be easy to get output by the gcexport.py-script.

Unfortunately Python demands a lot of parantheses that seem to be missing after the print-commands of gcexport.py.
After introducing "( )" I  got the next error (just trying  the "-h"):
"ImportError: cannot import name 'urlencode' from 'urllib' (C:\Users\Gerald\AppData\Local\Programs\Python\Python37\lib\urllib\__init__.py)"

This init-file is empty.
Is there something else necessary that the py-script runs?

Best regards
beta-L-user

**Comment by joetimmerman** [comment]
This repository isn't maintained anymore (and also doesn't support Python 3, as you've discovered). I believe the forks [here](https://github.com/moderation/garmin-connect-export/) and [here](https://github.com/pe-st/garmin-connect-export) are more current, I'd give those a try.

**Comment by beta-L-user** [comment]
Thanks, but unfortunately both lead to errors

- the second needs class “sort” which does not exist within python 3.7.0 

- the first gives the following output:

 

Welcome to Garmin Connect Exporter!

service=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin&webhost=https%3A%2F%2Fconnect.garmin.com&source=http%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&usernameShown=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=false

Request login page

Finish login page

Post login data

Finish login post

login ticket=ST-23876083-YpVUkH3VFdkLnECeZqc1-cas

Request authentication URL: https://connect.garmin.com/modern/activities?ticket=ST-23876083-YpVUkH3VFdkLnECeZqc1-cas

Finished authentication

Making activity request ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://connect.garmin.com/proxy/activity-search-service-1.2/json/activities?start=0&limit=3

Finished activity request ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Traceback (most recent call last):

  File "gcexport3.py", line 287, in <module>

    write_to_file(ARGS.directory + '/activities.json', RESULT.decode(), 'a')

  File "gcexport3.py", line 83, in write_to_file

    write_file.write(content)

  File "C:\Users\Gerald\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode

    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\u0113' in position 1211: character maps to <undefined>

 

best regards

 

gerald luza

 

Von: Joe Timmerman [mailto:notifications@github.com] 
Gesendet: Donnerstag, 26. Juli 2018 20:13
An: kjkjava/garmin-connect-export <garmin-connect-export@noreply.github.com>
Cc: beta-L-user <gerald@luza.at>; Author <author@noreply.github.com>
Betreff: Re: [kjkjava/garmin-connect-export] Errors starting the py-script (#47)

 

This repository isn't maintained anymore (and also doesn't support Python 3, as you've discovered). I believe the forks here <https://github.com/moderation/garmin-connect-export/>  and here <https://github.com/pe-st/garmin-connect-export>  are more current, I'd give those a try.

**Comment by yihong0618** [comment]
@joetimmerman  Thanks

**Comment by josepchaques** [comment]
Hi,

I have this problem:

/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'gcexport3.py': [Errno 2] No such file or directory

that I have to do?

Thanks
