### ISSUE TITLE
Payment required

### ISSUE THREAD

**Issue by sspeed22** [kjkjava/garmin-connect-export#50]
Ever since February 23, I'm getting a message from the Garmin api while using this that a payment is required and it doesn't complete.

Requesting Login ticket... Done. Ticket=ST-0234665-GucJ5WoJWl7eA30ye9Fr-cas
Authenticating... Done.
[ERROR] Failed to reach url https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=0&limit=20, error: HTTP Error 402: Payment Required
Querying list of activities 1..20...Traceback (most recent call last):
  File "C:\admintools\garmin-connect-export-3.0.2\gcexport.py", line 1061, in <module>
    main(sys.argv)
  File "C:\admintools\garmin-connect-export-3.0.2\gcexport.py", line 941, in main
    result = http_req_as_string(URL_GC_LIST + urlencode(search_params))
  File "C:\admintools\garmin-connect-export-3.0.2\gcexport.py", line 271, in http_req_as_string
    return http_req(url, post, headers).decode()
  File "C:\admintools\garmin-connect-export-3.0.2\gcexport.py", line 247, in http_req
    response = OPENER.open(request, data=post)
  File "C:\Users\mediaserver\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\mediaserver\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\mediaserver\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\mediaserver\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\mediaserver\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 402: Payment Required

**Comment by ChristianRohde** [comment]
I get the same Error with python2.7 on Ubuntu. No idea whats going on: is it a python problem or rather a garmin issue?

Connecting to Garmin Connect... Done.
Requesting Login ticket... Done. Ticket=ST-0974673-od5719HrqFysmZcUnJOD-cas
Authenticating... Done.
[ERROR] Failed to reach url https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=0&limit=10, error: HTTP Error 402: Payment Required
Querying list of activities 1..10...Traceback (most recent call last):
  File "/home/xxx/software/garmin-connect-export-develop/gcexport.py", line 1004, in <module>
    main(sys.argv)
  File "/home/xxx/software/garmin-connect-export-develop/gcexport.py", line 885, in main
    result = http_req(URL_GC_LIST + urlencode(search_params))
  File "/home/xxx/software/garmin-connect-export-develop/gcexport.py", line 204, in http_req
    response = OPENER.open(request, data=post)
  File "/home/xxx/miniconda3/envs/py2/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/xxx/miniconda3/envs/py2/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/xxx/miniconda3/envs/py2/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/home/xxx/miniconda3/envs/py2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/xxx/miniconda3/envs/py2/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 402: Payment Required

**Comment by guillaumechauvat** [comment]
Same here. I see this is an old issue, and it was working for me until a couple months ago.
